#!/bin/bash
#
# Script to build transpiler Docker image.
#
# Needs root privileges or 'docker' group membership

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
. "${SCRIPT_DIR}/../inc.constants"
. "${SCRIPT_DIR}/../inc.functions"


# Default values
DEFAULT_CMAKELINT=1.3.4.1

# Functions
function usage {
    echo -e "Usage: ${0} [OPTIONS]"
    echo -e "Options:"
    echo -e "  --cmakelint VERSION\t(default: ${DEFAULT_CMAKELINT})"
    echo -e "  --docker-push\t\t(optional)"
    exit 1
}


# Command-line arguments
cmakelint=${DEFAULT_CMAKELINT}
docker_push=
while [[ $# -gt 0 ]] ; do
    key="$1"
    case $key in
    --cmakelint)
        cmakelint="$2"
        shift # past argument
        ;;
    --docker-push)
        docker_push=true
        ;;
    -h|--help)
        usage
        shift # past argument
        ;;
    *) # unknown option
        ;;
    esac
    shift # past argument or value
done


# Let's roll
image_tag=${cmakelint}

safe docker build \
    --build-arg cmakelint=${cmakelint} \
    --tag ${DOCKER_IMAGE}:${image_tag} .
if [ ${docker_push} ] ; then
    safe docker push ${DOCKER_IMAGE}:${image_tag}
fi

# Update 'latest' tag if script argument match defaults
if [ ${cmakelint} = ${DEFAULT_CMAKELINT} ]; then
    safe docker tag ${DOCKER_IMAGE}:${image_tag} ${DOCKER_IMAGE}:latest
    if [ ${docker_push} ] ; then
        safe docker push ${DOCKER_IMAGE}:latest
    fi
fi
